server:
  port: 8081
keycloak:
  enabled: true
  realm: MedicalAnalysis
  auth-server-url: http://localhost:8019/auth
  ssl-required: none
  resource: MedicalAnalysis
  principal-attribute: username
  cors: true
  credentials:
    secret: 4ea8f459-d454-42f9-8db6-68b5b4d24e7c
  enable-basic-auth: true
  bearer-only: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
logging:
  level:
    org:
      springframework:
        security: DEBUG