server:
  port: 8081
keycloak:
  enabled: true
  realm: MedicalAnalysis
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: MedicalAnalysis
  principal-attribute: username
  cors: true
  credentials:
    secret: 681aa2b8-1df9-44d9-8729-b43949de6546
  bearer-only: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
logging:
  level:
    org:
      springframework:
        security: DEBUG

